# Generated by Django 4.2 on 2024-10-02 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=150, verbose_name="Место выполнения")),
                ("time", models.DateTimeField(verbose_name="Дата и время выполнения")),
                ("nice", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                ("periodicity", models.PositiveSmallIntegerField(default=1, verbose_name="Периодичность (дней)")),
                ("reward", models.CharField(max_length=150, verbose_name="Вознаграждение")),
                (
                    "duration",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Продолжительность выполнения (сек)"),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="Признак публикации")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
