# Generated by Django 4.2 on 2024-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="doing",
            field=models.CharField(default="Что-то сделать", max_length=150, verbose_name="Действие"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.SmallIntegerField(default=1, verbose_name="Продолжительность выполнения (сек)"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.SmallIntegerField(default=1, verbose_name="Периодичность (дней)"),
        ),
    ]
