# Generated by Django 4.2 on 2024-10-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_doing_alter_habit_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ("-id",), "verbose_name": ("привычка",), "verbose_name_plural": ("привычки",)},
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
