# Generated by Django 4.2 on 2024-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время выполнения"),
        ),
    ]
